# Generated by Django 4.1.3 on 2022-11-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_options_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Archive Card'),
        ),
    ]
