# Generated by Django 4.1.3 on 2022-11-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_is_archive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
