# Generated by Django 4.1.3 on 2022-12-03 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_folder_studyset_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyset',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_studyset', to=settings.AUTH_USER_MODEL),
        ),
    ]
