# Generated by Django 4.1.3 on 2022-12-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_studyset_card_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='study_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyset', to='cards.studyset'),
        ),
    ]
