# Generated by Django 4.1.3 on 2022-12-10 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_study_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='folder_studyset', to='cards.folder'),
        ),
    ]
